#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.configuration-cache=true

#Kotlin
kotlin.code.style=official

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Publish
GROUP=io.noties
POM_NAME=Debug
POM_ARTIFACT_ID=debug
POM_DESCRIPTION=KMP library for easy and extensible logging
POM_URL=https://github.com/noties/Debug
POM_SCM_URL=https://github.com/noties/Debug
POM_SCM_CONNECTION=scm:git:git://github.com/noties/Debug.git
POM_SCM_DEV_CONNECTION=scm:git:git://github.com/noties/Debug.git
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=noties
POM_DEVELOPER_NAME=Dimitry Ivanov